#

## NUMPY array and basics

In [2]:
import numpy as np

## Creating array from List

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


## List vs Array multiplication

In [5]:
py_list = [1,2,3]
print("Python list multiplication : ",py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication : ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time : ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time : ",time.time() - start)



Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

 List Operation Time :  0.28331446647644043

 Numpy Operation Time :  0.024314403533935547


## Creating Array from scratch

In [9]:
zeros = np.zeros((3,4))
print("Zero Array :  \n",zeros)


ones = np.ones((4,3))
print("one Array :  \n",ones)


full = np.full((2,3),6)     #constant array
print("Full Array :  \n",full)


random = np.random.random((3,2))   # random array
print("Random Array :  \n",random)


sequence = np.arange(0,11,2)      #  range wala array
print("Sequence Array :  \n",sequence)


Zero Array :  
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one Array :  
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array :  
 [[6 6 6]
 [6 6 6]]
Random Array :  
 [[0.52893663 0.22471096]
 [0.07449301 0.42741689]
 [0.69535269 0.20392208]]
Sequence Array :  
 [ 0  2  4  6  8 10]


## Vector, Matrix and Tensor

In [3]:
vector = np.array([1,2,3,4])
print("Vector :  ",vector)


matrix = np.array([[1,2,3],[4,5,6]])
print("\nMatrix :  ",matrix)


tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,0]]])   #Multi Demensional Array
print("\nTensor :  ",tensor)



Vector :   [1 2 3 4]

Matrix :   [[1 2 3]
 [4 5 6]]

Tensor :   [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 0]]]


## Array Properties

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape :  ",arr.shape)
print("Dimension :  ",arr.ndim)
print("Size :  ",arr.size)
print("DType :  ",arr.dtype)      # agr kohi aik bhi value change karain  tu type change hu jahey gi

arr = np.array([[1,2,3],[4,5,6.4]])
print("DType :  ",arr.dtype)


Shape :   (2, 3)
Dimension :   2
Size :   6
DType :   int64
DType :   float64


## Array Reshaping

In [15]:
arr = np.arange(12)
print("Original Array  ",arr)

reshaped = arr.reshape(3,4)
print("\nReshaped Array  ",reshaped)

# flatten (create copy)
flattened = reshaped.flatten()
print("\nFlattened Array  ",flattened)



# ravel(returns view , insted of copy)
reveled = reshaped.ravel()
print("\nRavel Array  ",reveled)


# Transpose
transpose = reshaped.T
print("Transpose of Array  ",transpose)







Original Array   [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array   [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array   [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravel Array   [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose of Array   [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
