## Numpy Array Operations

In [1]:
import numpy as np

## Indexing and Slicing

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ",arr[2:7])
print("With Step : ",arr[1:8:2])
print("Negative Indexing : ",arr[-6])

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative Indexing :  5


In [11]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element : ",arr2d[1,2])    # 1 row ka 2 element
print("Entire Row : ",arr2d[1])
print("Entire Column : ",arr2d[:,2])



Specific Element :  6
Entire Row :  [4 5 6]
Entire Column :  [3 6 9]


## Sorting

In [12]:
unsorted = np.array([4,3,5,1,2,6,4])
print("Sorted Array : ",np.sort(unsorted))


arr2dUnsorted = np.array([[3,1],[1,2],[2,3]])
print("\nSorted 2d Array by Column : ",np.sort(arr2dUnsorted,axis=0))

Sorted Array :  [1 2 3 4 4 5 6]

Sorted 2d Array by Column :  [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [13]:
numbers = np.arange(11)
evenNumbers = numbers[numbers % 2 == 0]
print("Even Numbers : ",evenNumbers)

Even Numbers :  [ 0  2  4  6  8 10]


## Filter with mask

In [14]:
mask = numbers > 5
print("Numbers greater then 5 : ",numbers[mask])

Numbers greater then 5 :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [15]:
indices = [0,2,4]
print(numbers[indices])

whereResult = np.where(numbers > 5)
print(whereResult)
print("Np Where : ",numbers[whereResult])


[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
Np Where :  [ 6  7  8  9 10]


In [16]:
conditionArray = np.where(numbers > 5,numbers*4,numbers)
print(conditionArray)

conditionArray = np.where(numbers > 5,"True","False")
print("\n",conditionArray)

[ 0  1  2  3  4  5 24 28 32 36 40]

 ['False' 'False' 'False' 'False' 'False' 'False' 'True' 'True' 'True'
 'True' 'True']


## Adding and removing data

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# aesa nhi karna 
combined = arr1 + arr2
print(combined)    #  yeh arrays ko add kar dey ga

combined = np.concatenate((arr1,arr2))
print(combined)


[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,0])

print("Compatibility shapes  : ",a.shape == b.shape)
print("Compatibility shapes  : ",a.shape == c.shape)

Compatibility shapes  :  True
Compatibility shapes  :  False


In [11]:
original = np.array([[1,2],[3,4]])
newRow = np.array([[5,6]])

withNewRow = np.vstack((original,newRow))
print(original)
print("\n With New Row  :",withNewRow)

newCol = np.array([[7],[8]])
withNewCol = np.hstack((original,newCol))
print("\n With New Column  :",withNewCol)


[[1 2]
 [3 4]]

 With New Row  : [[1 2]
 [3 4]
 [5 6]]

 With New Column  : [[1 2 7]
 [3 4 8]]


In [12]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array After Deletion : ",deleted)

Array After Deletion :  [1 2 4 5]
